sources:
  - name: public
    schema: public
    tables:
      - name: launches 

models:
  - name: launches
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
          - unique

    