sources:
  - name: public
    database: de_db
    schema: public
    tables:
      - name: launches
      - name: rockets
      

models:
  - name: launches
    columns:
      - name: id
        tests:
          - not_null
          - unique
      - name: name
        tests:
          - not_null
          - unique

    